### ISSUE TITLE
🚏 Roadmap

### ISSUE THREAD

**Issue by numb3r3** [jina-ai/clip-as-service#676]
Before 1.0, all new features and breaking changes will only bump the minor version. That also means the list below will only mention those features/breaking changes that are necessary for that minor version. Patch release is triggered whenever a bug is fixed. Hence they are not tracked/planned here in advance. Bugs solved in the patch release can be tracked in the [CHANGELOG](https://github.com/jina-ai/clip-as-service/blob/main/CHANGELOG.md).

## TODO

- [ ]  support multi-models with a single flow gateway (specify model via endpoint path e.g., `/zh_clip`, `/en_clip` ...)
- [ ]  add  `huggingface` clip model runtime backend 🔥
- [ ]  adopt to use `ONNXExecutor` as universe onnx runtime executor 🔥 https://github.com/jina-ai/executor-onnx-encoder

## `v0.5`

- [x]  k8s deployment (optional via **helm chart**) 
- [x] promethesus metric monitoring
- [ ] nebullvm backend
- [x] upload clip executor https://github.com/jina-ai/clip-as-service/issues/713 @ZiniuYu 

## `v0.4`:

- [x] add `rank` endpoints for all backends
- [x] benchmark results

## `v0.3` :
> on 04/29/2022

- [x]  apply onnxruntime optimization tricks (**optional**)
  -  how to dynamically setting `OMP_NUM_THREADS` based on the **batch_size**?
- [x] add `TensorRT` supporting without Triton inference service

## `v0.2` :
> on  04/11/2022
- [x]  validate/benchmark/profile on scalability (on both CPU/GPU)🔥
  - GPU utilization
  - detailed time profilings over flow
  - compared curve plot
